### ISSUE TITLE
Scripts to generate ranking data

### ISSUE THREAD

**Issue by gustavo-momente** [acelan/WCLRanks#1]
Hello, thanks a lot for this project! Would you mind share the scripts used to scrap the ranking data so that we could help expand to other realms ?

**Comment by Rootkit-** [comment]
I agree! I know lots of code easy mod for it.
Something like this...https://github.com/berg2043/WarcraftLogsPull

**Comment by omartism** [comment]
bump

**Comment by acelan** [comment]
I'm preparing the script, and will update here soon

**Comment by acelan** [comment]
Please check this repo
https://github.com/acelan/wcl_ant
